In [2]:
import numpy as np

Crie um array de zeros de dimensão 3x3:

In [3]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Crie um array de ums de dimensão 4x4x4:

In [7]:
ones_3d = np.ones((4,4,4))
ones_3d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Converta o array  arr = [1,2,3] para um array do numpy:

In [4]:
arr = [1,2,3]
np.array(arr)

array([1, 2, 3])

Crie um matriz identidade 3x3:

In [6]:
np.eye(3,dtype='int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Filtrando Números Pares
Crie um array arr contendo os números de 1 a 20. Usando boolean indexing, selecione apenas os números pares.

In [69]:
arr = np.arange(1,21)

arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Valores Maiores que a Média
Crie um array data de 15 números aleatórios entre 0 e 100. Use boolean indexing para selecionar os valores que são maiores que a média do array.

In [70]:
data = np.random.randint(0, 101, 15)
media = np.mean(data)

data[data > media]

array([60, 83, 88, 90, 80, 89])

### Substituindo Valores Negativos
Crie um array nums com 10 números inteiros aleatórios entre -10 e 10. Substitua todos os valores negativos por 0 usando boolean indexing.

In [73]:
data = np.random.randint(-10,10,15)
print(data)
data[data < 0] = 0

data

[ 1  2 -4  8  8 -2 -1 -3  7 -4 -7 -4  0  9  1]


array([1, 2, 0, 8, 8, 0, 0, 0, 7, 0, 0, 0, 0, 9, 1])

### Selecionando Elementos em uma Faixa
Crie um array values com 20 números inteiros aleatórios entre 0 e 100. Usando boolean indexing, selecione apenas os elementos que estão entre 30 e 70 (inclusive).

In [74]:
data = np.random.randint(0,100,20)

data[(data >= 30) & (data <= 70)]

array([69, 64, 53, 65, 39, 50, 34, 35])

In [80]:
arr = np.arange(15).reshape((3, 5))

np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])