Resposta [aqui](https://chatgpt.com/share/6733a07a-4018-8011-802f-ef9a696ac088)

In [2]:
import numpy as np

Questão 1
Crie um array NumPy 1D contendo os números de 0 a 9.

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Questão 2
Crie um array 2D (matriz) 3x3 preenchido com o número 7.

In [12]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Questão 3
Crie um array 3D com forma (2, 3, 4) contendo números inteiros aleatórios entre 0 e 20.

In [14]:
np.random.randint(0,20,(2,3,4))

array([[[10,  2,  5, 18],
        [15, 11,  1, 16],
        [ 6, 16, 18, 15]],

       [[12, 16, 17, 18],
        [ 4, 18,  0,  1],
        [ 8, 12,  6, 11]]])

Questão 4
Usando np.linspace(), crie um array de 5 números igualmente espaçados entre 10 e 20.

In [15]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

Questão 5
Crie um array de identidade (matriz identidade) de tamanho 4x4.

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Questão 6
Crie um array contendo os números [1.5, 2.5, 3.5] e converta-o para o tipo de dado inteiro.

In [27]:
arr = np.array([1.5,2.5,3.5])
arr.astype(int)

array([1, 2, 3])

Questão 7
Verifique o tipo de dado do array [True, False, True].

In [29]:
arr = np.array([True,False,True])

arr.dtype

dtype('bool')

Questão 8
Crie dois arrays: a = [1, 2, 3] e b = [4, 5, 6], e realize operações de adição, subtração, multiplicação e divisão entre eles.

In [31]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print(A+B)
print(B-A)
print(A*B)
print(B/A)

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]


Questão 9
Eleve ao quadrado todos os elementB-Aos do array [2, 4, 6].

In [32]:
A = np.array([2,4,6])

A**2

array([ 4, 16, 36])

Questão 10
Crie um array com números de 0 a 9 e extraia apenas os elementos nas posições pares.

In [35]:
A = np.arange(0,10)
A[::2]

array([0, 2, 4, 6, 8])

Questão 11
Dado um array 2D [[1, 2, 3], [4, 5, 6], [7, 8, 9]], extraia a segunda linha inteira.

In [36]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B[1]

array([4, 5, 6])

Questão 12
Crie um array com números de 0 a 9 e filtre apenas os números maiores que 5.

In [37]:
arr = np.arange(0,10)

arr[arr > 5]

array([6, 7, 8, 9])

Questão 13
Dado o array [5, -2, 7, -1, 0], substitua todos os valores negativos por 0.

In [38]:
arr = np.array([5, -2, 7, -1, 0])

arr[arr < 0] = 0

arr

array([5, 0, 7, 0, 0])

Questão 14
Dado um array a = [10, 20, 30, 40, 50], use fancy indexing para obter os elementos nas posições [0, 2, 4].

In [42]:
arr = np.arange(1,6)*10

arr[[0,2,4]]

array([10, 30, 50])

Questão 15
Crie uma matriz 4x4 de números aleatórios e selecione as linhas [1, 3] e colunas [0, 2].

In [51]:
arr = np.random.random((4,4))
print(arr)
arr[[1,3],:][:,[0,2]]

[[0.30421076 0.35490598 0.57097102 0.39533724]
 [0.92794088 0.18130032 0.10685413 0.05756138]
 [0.48815237 0.58047635 0.04456416 0.00230597]
 [0.93907559 0.58728903 0.5932116  0.07647314]]


array([[0.92794088, 0.10685413],
       [0.93907559, 0.5932116 ]])

Questão 16
Crie um array 2D de forma (2, 3) e transponha-o.

In [54]:
A = np.random.random((2,3))
A.T

array([[0.47508617, 0.14415164],
       [0.47161693, 0.21052991],
       [0.9480424 , 0.67268411]])

Questão 17
Crie um array 3D de forma (2, 3, 4) e troque os eixos 0 e 2.

In [ ]:
arr = np.random.random((2,3,4))

arr.transpose((2,1,0))

[[[0.60132997 0.26864599]
  [0.39373684 0.89319628]
  [0.67582705 0.79182449]]

 [[0.230878   0.42288861]
  [0.07419222 0.52492898]
  [0.10393492 0.66991505]]

 [[0.30001486 0.08317528]
  [0.31821769 0.15072596]
  [0.07421368 0.36334192]]

 [[0.73949795 0.12900417]
  [0.02298259 0.62184238]
  [0.21221049 0.99883064]]]


array([[[0.60132997, 0.26864599],
        [0.39373684, 0.89319628],
        [0.67582705, 0.79182449]],

       [[0.230878  , 0.42288861],
        [0.07419222, 0.52492898],
        [0.10393492, 0.66991505]],

       [[0.30001486, 0.08317528],
        [0.31821769, 0.15072596],
        [0.07421368, 0.36334192]],

       [[0.73949795, 0.12900417],
        [0.02298259, 0.62184238],
        [0.21221049, 0.99883064]]])

Questão 18
Gere um array de 5 números aleatórios de uma distribuição normal (média = 0, desvio padrão = 1).

In [ ]:
np.random.normal(loc=0,scale=1,size=5)

array([-1.10940507, -1.08279358, -1.33599866, -0.85892415, -1.90628044])

Questão 19
Crie um array de 10 números aleatórios inteiros entre 1 e 100 e determine o número máximo.

In [78]:
np.random.randint(1,100,size=10).max()

92

Questão 20
Crie um array a = [1, 4, 9, 16] e calcule a raiz quadrada de cada elemento.

In [82]:
arr = np.array([1,4,9,16])

np.sqrt(arr)

array([1., 2., 3., 4.])

Questão 21
Dado um array b = [0, π/2, π, 3π/2], aplique a função np.sin() para obter o seno de cada valor.

In [85]:
theta = [0, np.pi/2, np.pi, 3*np.pi/2]

np.sin(theta)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00])

Questão 22
Crie dois arrays a = [1, 2, 3] e b = [4, 5, 6] e calcule o produto escalar entre eles.

In [86]:
A = np.array([1,2,3])
B = np.array([4,5,6])

np.dot(A,B)

32

Questão 23
Usando broadcasting, crie um array 1D [1, 2, 3] e adicione-o a cada linha de uma matriz 3x3.

In [90]:
matrix = np.zeros((3,3))
arr = np.array([1,2,3])

result = matrix + arr
result

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

Questão 24
Crie um array [1, 2, 3, 4, 5] e substitua os valores pares por 0.

In [92]:
arr = np.array([1,2,3,4,5])

arr[arr % 2 == 0] = 0

arr

array([1, 0, 3, 0, 5])

Questão 25
Dado um array a = [1, -2, 3, -4, 5], substitua os valores negativos por seus valores absolutos.

In [97]:
arr = np.array([1, -2, 3, -4, 5])

arr[arr < 0] = np.abs(arr[arr < 0])

arr

array([1, 2, 3, 4, 5])

Questão 26
Crie um array a = [1, 2, 3, 4, 5] e calcule a média, a soma e o desvio padrão.

In [100]:
A = np.array([1,2,3,4,5])

np.mean(A)
np.sum(A)
np.std(A)

1.4142135623730951

Questão 27
Gere uma matriz 4x4 de números aleatórios e calcule a soma das colunas.

In [103]:
arr = np.random.random((4,4))

np.sum(arr,axis=0)

array([2.80037283, 2.50555156, 2.60405137, 1.94456831])

Questão 28
Crie um array [True, False, True, False] e conte quantos elementos são True.

In [106]:
arr_bol = np.array([True, False, True, False, True])

arr_bol.sum()

3

Questão 29
Dado o array a = [1, 2, 0, 4], verifique se todos os elementos são diferentes de zero.

In [110]:
arr = np.array([1,2,1,4])
np.all(arr != 0)

True

Questão 30
Crie um array [3, 1, 4, 2] e ordene-o em ordem crescente.


In [112]:
arr = np.array([3,1,4,2])

arr.sort()

arr

array([1, 2, 3, 4])

Questão 31
Dada a matriz [[5, 2], [1, 7]], ordene-a em ordem crescente por linhas.

In [116]:
matrix = np.array([[5, 2], [1, 7]])

print(matrix)
np.sort(matrix,axis=1)

[[5 2]
 [1 7]]


array([[2, 5],
       [1, 7]])

Questão 32
Dado o array [1, 2, 2, 3, 4, 4, 5], encontre os valores únicos.

In [119]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])

np.unique(arr)

array([1, 2, 3, 4, 5])

Questão 33
Crie dois arrays a = [1, 2, 3] e b = [3, 4, 5]. Encontre a interseção e a união desses arrays.

In [120]:
A = np.array([1,2,3])
B = np.array([3,4,5])

intersec = np.intersect1d(A,B)
union = np.union1d(A,B)

intersec,union

(array([3]), array([1, 2, 3, 4, 5]))

Questão 34
Crie um array a = [1, 2, 3, 4, 5] e salve-o em um arquivo chamado array.npy.

In [121]:
arr_sav = np.array([1,2,3,4,5])

np.save('exer34.npy',arr_sav)

Questão 35
Carregue o array salvo no arquivo array.npy.

In [122]:
arr_saved = np.load('exer34.npy')
arr_saved

array([1, 2, 3, 4, 5])

Questão 36
Crie duas matrizes A = [[1, 2], [3, 4]] e B = [[5, 6], [7, 8]]. Calcule a multiplicação de matrizes (produto matricial) A * B.

In [6]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


Questão 37
Encontre o determinante da matriz C = [[1, 2], [3, 4]].

In [12]:
C = np.array([[1,2],[3,4]])

np.linalg.det(C)

-2.0000000000000004

Questão 38
Crie um array 3x3 com números aleatórios e normalize-o (ou seja, subtraia a média e divida pelo desvio padrão).

In [20]:
X = np.random.random((3,3))

med = np.mean(X)
std = np.std(X)

normalized = (X - med)/std

normalized

array([[ 2.20842472,  0.49901192,  0.1527945 ],
       [ 0.70931771, -0.02112243, -0.79950071],
       [-0.90220188, -0.61631197, -1.23041186]])

Questão 39
Gere um array aleatório de 1000 elementos e calcule o percentil 90.

In [32]:
arr = np.random.random(1000)

np.percentile(arr,90)

0.8948208866901426

Questão 40
Gere uma matriz 4x4 com números aleatórios da distribuição uniforme no intervalo [0, 1).

In [33]:
arr40 = np.random.uniform(0,1,(4,4))
arr40

array([[0.11337631, 0.18407788, 0.19951778, 0.39387935],
       [0.85582741, 0.05277023, 0.36915652, 0.62894255],
       [0.52875885, 0.61407052, 0.57332642, 0.33206954],
       [0.68103722, 0.91873869, 0.43779426, 0.54282788]])

Questão 41
Fixe um seed para a geração de números aleatórios e gere um array de 5 elementos. Verifique se o resultado é reproduzível.

In [54]:
np.random.seed(42)

np.random.random(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

Questão 42
Dado um array a = [2, -3, 4, -5], aplique a função np.abs() para obter os valores absolutos.

In [56]:
arr42 = np.array([2,-3,4,-5])

np.abs(arr42)

array([2, 3, 4, 5])

Questão 43
Use a função np.maximum() para comparar os arrays x = [2, 7, 3] e y = [1, 5, 8] e retornar o máximo de cada posição.

In [58]:
x = np.array([2,7,3])
y = np.array([1,5,8])

np.maximum(x,y)

array([2, 7, 8])

Questão 44
Dado um array a = np.arange(1, 10).reshape(3, 3), calcule o quadrado de cada elemento usando a função np.power().

In [61]:
a = np.arange(1,10).reshape(3,3)
np.power(a,2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

Questão 45
Crie dois arrays a = [0, 1, 2] e b = [2, 0, 2]. Calcule o produto elemento a elemento usando np.multiply().

In [62]:
a = np.array([0,1,2])
b = np.array([2,0,2])

np.multiply(a,b)

array([0, 0, 4])

Questão 46
Gere um array aleatório de forma (3, 4) e calcule a média por linhas e por colunas.

In [68]:
arr = np.random.random((3,4))

print(np.mean(arr,axis=1))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=(0,1)))
print(np.mean(arr))

[0.62577352 0.23880444 0.43444359]
[0.45405308 0.49062159 0.53465263 0.25270143]
0.4330071846169162
0.4330071846169162


Questão 47
Calcule a variância e a mediana dos elementos de um array [10, 20, 30, 40, 50].

In [70]:
arr47 = np.array([10,20,30,40,50])

var = np.var(arr47)
mediana = np.median(arr47)

var, mediana

(200.0, 30.0)

Questão 48
Resolva o sistema de equações lineares:

2
𝑥
+
3
𝑦
=
8
5
𝑥
+
𝑦
=
7
2x+3y=8
5x+y=7
Usando a função np.linalg.solve().

In [76]:
v1 = np.array([2,3,8])
v2 = np.array([5,1,7])

M = [v1[:-1],v2[:-1]]
S = [v1[-1],v2[-1]]
print(M)
print(S)
np.linalg.solve(M,S)

[array([2, 3]), array([5, 1])]
[8, 7]


array([1., 2.])

Questão 49
Encontre os autovalores e autovetores da matriz M = [[2, 0], [0, 3]].

In [80]:
M = np.array([[2,0],[0,3]])

eigenvalues, eigenvectors = np.linalg.eig(M)
eigenvalues, eigenvectors

(array([2., 3.]),
 array([[1., 0.],
        [0., 1.]]))